Update patch set 13
Patch Set 13:

> Patch Set 13: Verified-1
> 
> Fails with: 
> [2020-09-18T00:05:28.528+0100] [ReceiveCommits-5[java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4fa25dab]-for-SSH git-receive-pack /load-test (admin)] ERROR com.google.gerrit.server.extensions.events.RevisionCreated : Couldn't fire event [CONTEXT RECEIVE_ID="load-test-1600383928395-f792b80b" project="load-test" ]
> com.google.gerrit.exceptions.StorageException: java.lang.IllegalStateException: ChronicleMap{name=mergeability, file=/Users/lucamilanesio/gerrit-master/cache/mergeability.dat, identityHashCode=1326541986}: Attempt to allocate #2 extra segment tier, 1 is maximum.
> Possible reasons include:
>  - you have forgotten to configure (or configured wrong) builder.entries() number
>  - same regarding other sizing Chronicle Hash configurations, most likely maxBloatFactor(), averageKeySize(), or averageValueSize()
>  - keys, inserted into the ChronicleHash, are distributed suspiciously bad. This might be a DOS attack
> 	at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:377)
> 	at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:282)
> 	at com.google.gerrit.server.change.ChangeJson.format(ChangeJson.java:278)
> 	at com.google.gerrit.server.extensions.events.EventUtil.changeInfo(EventUtil.java:88)
> 	at com.google.gerrit.server.extensions.events.RevisionCreated.fire(RevisionCreated.java:80)
> 	at com.google.gerrit.server.change.ChangeInserter.postUpdate(ChangeInserter.java:462)
> 	at com.google.gerrit.server.update.BatchUpdate.postUpdate(BatchUpdate.java:670)
> 	at com.google.gerrit.server.update.BatchUpdate.executePostOps(BatchUpdate.java:652)
> 	at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:171)
> 	at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:395)
> 	at com.google.gerrit.server.update.BatchUpdate.execute(BatchUpdate.java:399)
> 	at com.google.gerrit.server.git.receive.ReceiveCommits.insertChangesAndPatchSets(ReceiveCommits.java:955)
> 	at com.google.gerrit.server.git.receive.ReceiveCommits.processCommandsUnsafe(ReceiveCommits.java:685)
> 	at com.google.gerrit.server.git.receive.ReceiveCommits.processCommands(ReceiveCommits.java:601)
> 	at com.google.gerrit.server.git.receive.AsyncReceiveCommits.lambda$preReceive$3(AsyncReceiveCommits.java:370)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at com.google.gerrit.server.util.RequestScopePropagator.lambda$cleanup$1(RequestScopePropagator.java:182)
> 	at com.google.gerrit.server.util.RequestScopePropagator.lambda$context$0(RequestScopePropagator.java:170)
> 	at com.google.gerrit.server.util.ThreadLocalRequestScopePropagator.lambda$wrapImpl$0(ThreadLocalRequestScopePropagator.java:45)
> 	at com.google.gerrit.server.util.RequestScopePropagator$1.call(RequestScopePropagator.java:85)
> 	at com.google.gerrit.server.util.RequestScopePropagator$2.run(RequestScopePropagator.java:116)
> 	at com.google.gerrit.server.logging.LoggingContextAwareRunnable.run(LoggingContextAwareRunnable.java:110)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:612)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IllegalStateException: ChronicleMap{name=mergeability, file=/Users/lucamilanesio/gerrit-master/cache/mergeability.dat, identityHashCode=1326541986}: Attempt to allocate #2 extra segment tier, 1 is maximum.
> Possible reasons include:
>  - you have forgotten to configure (or configured wrong) builder.entries() number
>  - same regarding other sizing Chronicle Hash configurations, most likely maxBloatFactor(), averageKeySize(), or averageValueSize()
>  - keys, inserted into the ChronicleHash, are distributed suspiciously bad. This might be a DOS attack

Yes this is because if you used the defaults (1 byte), which is very different from the _actual_ size of mergeability cache keys/values. The pre-allocation that chronicle-map does is not enough when the number of entries and their size is different from the declared one.

I ran some heuristic to understand the size of some key/values.
Try to configure the following in gerrit.config.

[cache "accounts"]
        avgKeySize=30
        avgValueSize=100

[cache "external_ids_map"]
        avgKeySize=24
        avgValueSize=200

[cache "web_sessions"]
        avgKeySize=50
        avgValueSize=170

[cache "diff"]
        avgKeySize=100
        avgValueSize=500

[cache "mergeability"]
        avgKeySize=20
        avgValueSize=500

[cache "persisted_projects"]
        avgKeySize=60
        avgValueSize=4000

[cache "change_notes"]
        avgKeySize=50
        avgValueSize=1000

Values might need to be tweaked depending on the size of your changes, cached-projects, etc.
But it should work in an OOTB installation.

This method can be used to find out the size of key/pairs in your cache [1].

```
public static <K, V> void printMapStats(ChronicleMap<K, V> map) {
        for (int i = 0; i < map.segments(); i++) {
            try (MapSegmentContext<K, V, ?> c = map.segmentContext(i)) {
                System.out.printf("segment %d contains %d entries\n", i, c.size());
                c.forEachSegmentEntry(e -> System.out.printf("%s, %d bytes -> %s, %d bytes\n",
                        e.key(), e.key().size(), e.value(), e.value().size()));
            }
        }
    }
```

[1]https://github.com/OpenHFT/Chronicle-Map/blob/master/docs/CM_Tutorial_Behaviour.adoc#example---monitor-chronicle-map-statistics

Patch-set: 13
Reviewer: Gerrit User 1015244 <1015244@d5d70762-12d0-45a1-890d-524b12d3f735>