Update patch set 13
Patch Set 13:

The cache is functional, however there's an issue with the cache of OauthTokenCache, where the cache cannot be loaded back from the persisted file cache, if one exists.

I couldn't get to the bottom of it unfortunately, but it seems to be caused by this serializer conversion[1], which is *only* used for OauthTokenCache, that's why it is the only one affected.

https://gerrit.googlesource.com/gerrit/+/refs/heads/master/java/com/google/gerrit/server/auth/oauth/OAuthTokenCache.java#50


```[2020-09-17 16:08:40,056] [main] WARN  net.openhft.chronicle.wire.WireMarshaller$ObjectFieldAccess : Unable to parse field: forwardFunction, as a marshallable as it is net.openhft.chronicle.core.io.IORuntimeException: Trying to read marshallable class com.sun.proxy.$Proxy185 at [pos: 2188, rlim: 2290, wlim: 4229, cap: 4229 ] rit.server.auth.oauth.OAuthTokenCache$1$$Lambda$150/726107869 { ǁ}, backwardFunction: !com.google.gerrit.server.auth.oauth.OAuthT... expected to find a {
net.openhft.chronicle.core.io.IORuntimeException: Trying to read marshallable class com.sun.proxy.$Proxy184 at [pos: 2188, rlim: 2290, wlim: 4229, cap: 4229 ] rit.server.auth.oauth.OAuthTokenCache$1$$Lambda$150/726107869 { ǁ}, backwardFunction: !com.google.gerrit.server.auth.oauth.OAuthT... expected to find a {

Patch-set: 13
Reviewer: Gerrit User 1015244 <1015244@d5d70762-12d0-45a1-890d-524b12d3f735>